# -*- coding: utf-8 -*-
"""股票筛选Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__n4uhN4mVoF0Jh5urL-reB8cxzKpyPl

### SEPA 策略筛选原则 (Three-Cycle Screening Principles)

1. **周线趋势闸门 (Weekly Gate)**:
    * **均线确认**: MA20 和 MA50 必须近 12 周持续向上。
    * **多头排列**: 价格 > MA20 > MA50。
    * **超买限制**: 收盘价与 MA50 的乖离率需控制在阈值内 (默认 1.7)，防止追高。

2. **日线核心筛选 (Daily Core)**:
    * **多头排列**: 满足 MA50 > MA150 > MA200 的典型 SEPA 排列。
    * **双重相对强度 (RS)**: 在 20 日和 250 日两个维度上均需跑赢大盘 (SPY)。
    * **突破与放量**: 必须有效突破前 10 日高点，且昨日成交量达到 20 日均线的 1.0 倍以上。
    * **技术指标**: 限制日线乖离率 (MA200) 和 RSI14 强度，确保安全边际。

3. **小时线择时确认 (Hourly Timing)**:
    * **低吸机会**: 当小时线 MA20 > MA60 且 RSI 处于 30-70 的中性偏低区间时提示建仓。
    * **风险预警**: 针对短期严重超买 (RSI > 75) 或趋势未确认的情况进行过滤。

4. **执行与风险管理**:
    * **自动化逻辑**: 脚本读取 CSV 标的池，通过 Yahoo Finance 实时抓取三周期数据。
    * **仓位建议**: 默认推荐最强的前 3 只标的。
    * **止损与保本**: 严格执行 -7% 止损位和 +14% 保本锁利位。
"""

!pip install -q finvizfinance

# @title SEPA 策略全参数交互式配置区
# @markdown ### 【初筛核心参数】
MARKET_CAP_MIN = 5000 # @param {type:"number"}
# @markdown 最小市值（单位：百万美元，默认50亿）
MARKET_CAP_MAX = 200000 # @param {type:"number"}
# @markdown 最大市值（单位：百万美元，默认2000亿）
PRICE_MIN = 5 # @param {type:"number"}
# @markdown 最低股价（美元）
DAILY_VOLUME_MIN = 5 # @param {type:"number"}
# @markdown 单日最低成交量（单位：百万股，默认500万股 - 注意：Finviz预设最大选项为Over 2M）
AVG_VOLUME_MIN = 5 # @param {type:"number"}
# @markdown 20日平均最低成交量（单位：百万股，默认500万股 - 注意：Finviz预设最大选项为Over 2M）
MA200_RISING_DAYS = 43 # @param {type:"number"}
# @markdown MA200持续向上的最小交易日数
IPO_MIN_YEAR = 1 # @param {type:"number"}
# @markdown 上市最短时间（年）
EXCLUDE_INDUSTRIES = ["Banks", "Insurance", "Utilities", "Oil & Gas", "Steel", "Shipping", "Coal"] # @param {type:"raw"}
# @markdown 需排除的行业列表

# @markdown ### 【周期筛选阈值】
WEEKLY_BIAS_LIMIT = 1.4 # @param {type:"number"}
# @markdown 周线乖离率上限：收盘价与周线MA50的最大允许值
DAILY_BIAS_LIMIT = 1.5 # @param {type:"number"}
# @markdown 日线乖离率上限：收盘价与日线MA200的最大允许值
DAILY_RSI_LIMIT = 70 # @param {type:"integer"}
# @markdown 日线RSI超买上限：14日周期RSI最大值

# @markdown ### 【小时线择时参数】
HOURLY_RSI_OVERBOUGHT = 75 # @param {type:"integer"}
# @markdown 小时线RSI超买阈值
HOURLY_RSI_LOW = 30 # @param {type:"integer"}
# @markdown 小时线低吸区间RSI下限
HOURLY_RSI_HIGH = 70 # @param {type:"integer"}
# @markdown 小时线低吸区间RSI上限

import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta
from finvizfinance.screener.overview import Overview
import io
import warnings
warnings.filterwarnings('ignore')

# ===================== 核心配置 (完全保留) =====================
BENCHMARK, MAX_POSITIONS = "SPY", 3
STOP_LOSS_PCT, BREAK_EVEN_PCT = 0.07, 0.14
VOL_MULT = 1.0

def get_finviz_screened_tickers():
    """封装finviz自动初筛函数，修复API参数格式，增加Python二次校验"""
    try:
        f_screener = Overview()
        # 修复点：IPO Date 严格匹配官方选项 'More than a year ago'
        filters_dict = {
            'Market Cap.': '+Large (over $10bln)',
            'Price': 'Over $5',
            'Average Volume': 'Over 2M',
            'Current Volume': 'Over 2M',
            'IPO Date': 'More than a year ago',
            '200-Day Simple Moving Average': 'Price above SMA200'
        }

        f_screener.set_filter(filters_dict=filters_dict)
        df_res = f_screener.screener_view()

        if df_res is None or df_res.empty:
            return []

        # 排除特定行业
        if 'Industry' in df_res.columns:
            df_res = df_res[~df_res['Industry'].str.contains('|'.join(EXCLUDE_INDUSTRIES), case=False, na=False)]

        initial_tickers = df_res['Ticker'].tolist()
        final_tickers = []

        # Python轻量市值二次校验 (确保符合 5B-200B 核心需求)
        print(f"🔍 正在进行市值二次校验 (目标范围: {MARKET_CAP_MIN}M - {MARKET_CAP_MAX}M)...")
        for ticker in initial_tickers:
            try:
                info = yf.Ticker(ticker).fast_info
                mkt_cap_m = info['marketCap'] / 1e6
                if MARKET_CAP_MIN <= mkt_cap_m <= MARKET_CAP_MAX:
                    final_tickers.append(ticker)
            except: continue

        print(f"✅ finviz初筛完成，最终获取到 {len(final_tickers)} 只符合条件的标的")
        return final_tickers
    except Exception as e:
        print(f"❌ finviz初筛接口调用失败: {e}")
        return []

def get_data(symbol: str, interval='1d'):
    """获取数据的核心函数 (100%保留)"""
    period = "2y" if interval == '1wk' else "1y"
    if interval == '1h': period = "2y"
    df = yf.download(symbol, period=period, interval=interval, progress=False, auto_adjust=True)
    if df.empty: return df
    if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.get_level_values(0)
    return df

def check_weekly_gate(ticker, df_w):
    """周线SEPA闸门函数 (100%保留)"""
    if len(df_w) < 52: return False, "周线数据不足一年"
    df_w['MA20'] = df_w['Close'].rolling(20).mean()
    df_w['MA50'] = df_w['Close'].rolling(50).mean()
    curr = df_w.iloc[-1]
    prev_12 = df_w['MA20'].iloc[-12:]
    prev_12_50 = df_w['MA50'].iloc[-12:]
    if not (prev_12.is_monotonic_increasing and prev_12_50.is_monotonic_increasing):
        return False, "周线均线未持续向上"
    if not (curr['Close'] > curr['MA20'] > curr['MA50']):
        return False, "周线价格未站稳均线或排列错误"
    if curr['Close'] / curr['MA50'] > WEEKLY_BIAS_LIMIT:
        return False, f"周线超买(乖离率>{WEEKLY_BIAS_LIMIT})"
    return True, "周线通过"

def check_daily_core(ticker, df, spy_df):
    """日线SEPA选股函数 (100%保留)"""
    if len(df) < 250: return False, "日线历史数据不足", None
    df['MA50'] = df['Close'].rolling(50).mean()
    df['MA150'] = df['Close'].rolling(150).mean()
    df['MA200'] = df['Close'].rolling(200).mean()
    df['VOL_MA20'] = df['Volume'].rolling(20).mean()
    df['MIN_VOL20'] = df['Volume'].rolling(20).min()
    df['HIGH10_PREV'] = df['High'].shift(1).rolling(10).max()
    delta = df['Close'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
    df['RSI14'] = 100 - (100 / (1 + (gain / loss)))
    common = df.index.intersection(spy_df.index)
    if len(common) < 2: return False, "指数数据对齐失败", None
    t = df.loc[common].iloc[-2]
    if not (t['MA50'] > t['MA150'] > t['MA200']): return False, "日线均线未完全多头排列", None
    rs20_stock = df['Close'].pct_change(20).loc[common].iloc[-2]
    rs20_spy = spy_df['Close'].pct_change(20).loc[common].iloc[-2]
    rs250_stock = df['Close'].pct_change(250).loc[common].iloc[-2]
    rs250_spy = spy_df['Close'].pct_change(250).loc[common].iloc[-2]
    if rs20_stock <= rs20_spy or rs250_stock <= rs250_spy: return False, "相对强度(RS)未跑赢大盘", None
    if t['Close'] <= t['HIGH10_PREV']: return False, "未有效突破前10日高点", None
    if t['Volume'] < t['VOL_MA20'] * VOL_MULT or t['MIN_VOL20'] < 500000: return False, "成交量未放量或流动性不足", None
    if t['Close'] / t['MA200'] > DAILY_BIAS_LIMIT or t['RSI14'] >= DAILY_RSI_LIMIT: return False, "日线过度超买", None
    return True, "日线通过", t

def get_hourly_timing(ticker):
    """小时线择时提示 (100%保留)"""
    try:
        df_h = get_data(ticker, interval='1h')
        if len(df_h) < 60: return "小时线数据不足"
        df_h['MA20'] = df_h['Close'].rolling(20).mean()
        df_h['MA60'] = df_h['Close'].rolling(60).mean()
        delta = df_h['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rsi = (100 - (100 / (1 + gain/loss))).iloc[-1]
        curr = df_h.iloc[-1]
        if curr['MA20'] > curr['MA60'] and HOURLY_RSI_LOW <= rsi <= HOURLY_RSI_HIGH and curr['Close'] > curr['MA20']:
            return "✅ 小时线择时信号：当前是低吸机会"
        elif rsi > HOURLY_RSI_OVERBOUGHT:
            return "⚠️ 小时线择时信号：短期严重超买"
        else: return "ℹ️ 小时线择时信号：中性"
    except: return "小时线择时计算出错"

def run_sepa_bot():
    """全自动化运行流程"""
    tickers = get_finviz_screened_tickers()
    if not tickers:
        print("❌ finviz初筛无符合条件的标的，请检查参数")
        return

    spy_df = get_data(BENCHMARK)
    buy_signals = []

    for ticker in tickers:
        try:
            df_w = get_data(ticker, interval='1wk')
            pass_w, msg_w = check_weekly_gate(ticker, df_w)
            if not pass_w: continue

            df_d = get_data(ticker, interval='1d')
            pass_d, msg_d, last_row = check_daily_core(ticker, df_d, spy_df)
            if not pass_d: continue

            timing_msg = get_hourly_timing(ticker)
            p = last_row['Close']
            buy_signals.append({
                "ID": ticker, "Price": round(p, 2), "SL": round(p*(1-STOP_LOSS_PCT), 2),
                "BE": round(p*(1+BREAK_EVEN_PCT), 2), "Msg": f"{msg_w} | {msg_d}", "Timing": timing_msg
            })
        except: continue

    print("\n" + "="*15 + " 🔴 三周期SEPA明日入场推荐 " + "="*15)
    if not buy_signals: print("→ 暂无符合标的")
    else:
        for i in buy_signals[:MAX_POSITIONS]:
            print(f"• {i['ID']} | 触发价: {i['Price']} | 7%止损: {i['SL']} | 14%保本位: {i['BE']}")
            print(f"  ├─ 状态: {i['Msg']}\n  └─ 建议: {i['Timing']}")

if __name__ == '__main__':
    run_sepa_bot()